apiVersion: v1
kind: Pod
metadata:
  name: game-config-multi-env-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      envFrom:
        - configMapRef:
            name: config-multi-env-files
