apiVersion: v1
kind: Namespace
metadata:
  name: docs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-docs
  name: kubernetes-docs
  namespace: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-docs
  strategy: {}
  template:
    metadata:
      labels:
        app: kubernetes-docs
    spec:
      containers:
      - image: ikauzak/kubernetes-course-docs:v1.0.1
        name: kubernetes-course-docs
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes-docs
  name: kubernetes-docs
  namespace: docs
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: kubernetes-docs
  type: NodePort
