apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-hostname
  name: test-hostname-clusterip
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-hostname
  type: ClusterIP
