apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-hostname
  name: test-hostname-nodeport
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: test-hostname
  type: NodePort

