apiVersion: v1
kind: Namespace
metadata:
  name: website
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: website
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: website
data:
  index.html: |
    <html>
    <h1>Ingress</h1>
    </br>
    <h1>Vc conseguiu expor essa app via ingress!</h1>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-deploy
  namespace: website
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-index-file
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-index-file
        configMap:
          name: index-html-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: marketing-svc
  namespace: website
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: nginx
