apiVersion: v1
kind: Pod
metadata:
  labels:
    run: order-processing
  name: order-processing
spec:
  containers:
  - image: nginx
    name: order-processing
    env: #ajuste os valores consumindo os valores da secret order-credentials.yaml 
      - name: DB_USERNAME
        value: admin
      - name: DB_PASSWORD
        value: KubernetesTr@ining
  restartPolicy: Always
