apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketing-ingress
  namespace: website
spec:
  ingressClassName: nginx
  rules:
  - host: front.cluster.local
    http:
      paths:
      - backend:
          service:
            name: marketing-svc 
            port:
              number: 8000
        path: /
        pathType: Prefix
