apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketing-ingress
  namespace: website
spec:
  ingressClassName: nginx
  rules:
    - host: # hostname da aplicação ex: teste.exemplo.com
    http:
      paths:
      - backend:
          service:
            name: # Nome do serviço da aplicação frontend marketing 
            port:
              number: # Porta do serviço correspondente
        path: /
        pathType: Prefix
